### ISSUE TITLE
Bug das datas

### ISSUE THREAD

**Issue by JoaoAlisonTI** [Kayke-Ti/SIBI_V2#1]
![IMG_20240224_111505](https://github.com/Kayke-Ti/SIBI_V2/assets/104854246/a8ac839d-734f-4ff5-a5b7-03ae9f81fe9b)
 
Troca essa parte aí acima do código por essa aqui debaixo e testa

`const formattedRequest = {
  ...updatedRequest,
  dataInicio: format(new Date(updatedRequest.dataInicio), "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"),
  dataDevolucao: format(new Date(updatedRequest.dataDevolucao), "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"),
};
`

Pelo o que eu vi, o erro pode tá relacionado com a especificação do fuso horário. No código só tá a data mas não tem a especificação do fuso horário, que são diferentes, a nossa aqui do Brasil e dos EUA. Aí como não tem essa especificação o serviço de hospedagem escolhe o padrão do servidor.

**Comment by Kayke-Ti** [comment]
Bug Resolvido @JoaoAlisonTI.
